export {InputVariantOne} from "./variant.one"
export {InputVariantTwo} from "./variant.two"
export {InputVariantFive} from "./variant.five"
export {InputVariantFour} from "./variant.four"
export {InputVariantThree} from "./variant.three"