/* eslint-disable react/react-in-jsx-scope */
export default function Head() {
  return (
    <>
      <title>Genesis</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />

      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <link rel="icon" href="/favicon.ico" />
    </>
  );
}
